# XYGo Backend Code Generator
# Usage: .\gen.ps1 [dao|service|logic|all|build|run|clean|help]

param([string]$Command = "help")

function GenDao {
    Write-Host "Generating DAO layer..." -ForegroundColor Yellow
    gf gen dao
}

function GenService {
    Write-Host "Generating Service layer..." -ForegroundColor Yellow
    gf gen service
}

function GenLogic {
    Write-Host "Generating logic.go..." -ForegroundColor Yellow
    
    $header = @"
// ==========================================================================
// Code generated by gen.ps1. DO NOT EDIT manually.
// Run '.\gen.ps1 logic' to regenerate this file.
// ==========================================================================

package logic

import (
"@
    
    $logicDirs = Get-ChildItem -Path "internal/logic" -Directory | 
                 Where-Object { $_.Name -ne "." -and $_.Name -ne ".." } |
                 Sort-Object Name
    
    $imports = $logicDirs | ForEach-Object { "`t_ `"xygo/internal/logic/$($_.Name)`"" }
    
    $content = $header + "`n" + ($imports -join "`n") + "`n)"
    
    [System.IO.File]::WriteAllText("internal/logic/logic.go", $content, [System.Text.Encoding]::UTF8)
    
    Write-Host "Generated logic.go with $($logicDirs.Count) modules" -ForegroundColor Green
}

function GenAll {
    Write-Host "========== Starting Code Generation ==========" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Step 1/3: Generating DAO layer..." -ForegroundColor Yellow
    GenDao
    Write-Host ""
    Write-Host "Step 2/3: Generating logic.go..." -ForegroundColor Yellow
    GenLogic
    Write-Host ""
    Write-Host "Step 3/3: Generating Service layer..." -ForegroundColor Yellow
    GenService
    Write-Host ""
    Write-Host "========== Code Generation Complete ==========" -ForegroundColor Green
}

function BuildProject {
    Write-Host "Building project..." -ForegroundColor Yellow
    go build -o xygo.exe .
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Build successful" -ForegroundColor Green
    } else {
        Write-Host "Build failed" -ForegroundColor Red
    }
}

function RunProject {
    Write-Host "Running with hot reload..." -ForegroundColor Yellow
    gf run main.go
}

function CleanBackup {
    Write-Host "Cleaning backup files..." -ForegroundColor Yellow
    Remove-Item -Path "internal/service/*.bak" -ErrorAction SilentlyContinue
    Write-Host "Backup files cleaned" -ForegroundColor Green
}

function ShowHelp {
    Write-Host "XYGo Backend Development Commands:" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  .\gen.ps1 dao       Generate DAO layer (gf gen dao)"
    Write-Host "  .\gen.ps1 service   Generate Service layer (gf gen service)"
    Write-Host "  .\gen.ps1 logic     Auto-generate logic.go imports"
    Write-Host "  .\gen.ps1 all       Generate all (dao + logic + service)"
    Write-Host "  .\gen.ps1 build     Build project"
    Write-Host "  .\gen.ps1 run       Run with hot reload"
    Write-Host "  .\gen.ps1 clean     Clean backup files"
    Write-Host ""
}

switch ($Command.ToLower()) {
    "dao" { GenDao }
    "service" { GenService }
    "logic" { GenLogic }
    "all" { GenAll }
    "build" { BuildProject }
    "run" { RunProject }
    "clean" { CleanBackup }
    default { ShowHelp }
}
