// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// adminFieldPermDao is the data access object for the table xy_admin_field_perm.
// You can define custom methods on it to extend its functionality as needed.
type adminFieldPermDao struct {
	*internal.AdminFieldPermDao
}

var (
	// AdminFieldPerm is a globally accessible object for table xy_admin_field_perm operations.
	AdminFieldPerm = adminFieldPermDao{internal.NewAdminFieldPermDao()}
)

// Add your custom methods and functionality below.
