// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// adminDeptClosureDao is the data access object for the table xy_admin_dept_closure.
// You can define custom methods on it to extend its functionality as needed.
type adminDeptClosureDao struct {
	*internal.AdminDeptClosureDao
}

var (
	// AdminDeptClosure is a globally accessible object for table xy_admin_dept_closure operations.
	AdminDeptClosure = adminDeptClosureDao{internal.NewAdminDeptClosureDao()}
)

// Add your custom methods and functionality below.
