// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// adminUserPostDao is the data access object for the table xy_admin_user_post.
// You can define custom methods on it to extend its functionality as needed.
type adminUserPostDao struct {
	*internal.AdminUserPostDao
}

var (
	// AdminUserPost is a globally accessible object for table xy_admin_user_post operations.
	AdminUserPost = adminUserPostDao{internal.NewAdminUserPostDao()}
)

// Add your custom methods and functionality below.
