// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// captchaDao is the data access object for the table xy_captcha.
// You can define custom methods on it to extend its functionality as needed.
type captchaDao struct {
	*internal.CaptchaDao
}

var (
	// Captcha is a globally accessible object for table xy_captcha operations.
	Captcha = captchaDao{internal.NewCaptchaDao()}
)

// Add your custom methods and functionality below.
