// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// cmsDocDao is the data access object for the table xy_cms_doc.
// You can define custom methods on it to extend its functionality as needed.
type cmsDocDao struct {
	*internal.CmsDocDao
}

var (
	// CmsDoc is a globally accessible object for table xy_cms_doc operations.
	CmsDoc = cmsDocDao{internal.NewCmsDocDao()}
)

// Add your custom methods and functionality below.
