// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// cmsCaseDao is the data access object for the table xy_cms_case.
// You can define custom methods on it to extend its functionality as needed.
type cmsCaseDao struct {
	*internal.CmsCaseDao
}

var (
	// CmsCase is a globally accessible object for table xy_cms_case operations.
	CmsCase = cmsCaseDao{internal.NewCmsCaseDao()}
)

// Add your custom methods and functionality below.
