// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// cmsDocCategoryDao is the data access object for the table xy_cms_doc_category.
// You can define custom methods on it to extend its functionality as needed.
type cmsDocCategoryDao struct {
	*internal.CmsDocCategoryDao
}

var (
	// CmsDocCategory is a globally accessible object for table xy_cms_doc_category operations.
	CmsDocCategory = cmsDocCategoryDao{internal.NewCmsDocCategoryDao()}
)

// Add your custom methods and functionality below.
