// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// cmsCaseCategoryDao is the data access object for the table xy_cms_case_category.
// You can define custom methods on it to extend its functionality as needed.
type cmsCaseCategoryDao struct {
	*internal.CmsCaseCategoryDao
}

var (
	// CmsCaseCategory is a globally accessible object for table xy_cms_case_category operations.
	CmsCaseCategory = cmsCaseCategoryDao{internal.NewCmsCaseCategoryDao()}
)

// Add your custom methods and functionality below.
