// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// communityPostDao is the data access object for the table xy_community_post.
// You can define custom methods on it to extend its functionality as needed.
type communityPostDao struct {
	*internal.CommunityPostDao
}

var (
	// CommunityPost is a globally accessible object for table xy_community_post operations.
	CommunityPost = communityPostDao{internal.NewCommunityPostDao()}
)

// Add your custom methods and functionality below.
