// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// communityLikeDao is the data access object for the table xy_community_like.
// You can define custom methods on it to extend its functionality as needed.
type communityLikeDao struct {
	*internal.CommunityLikeDao
}

var (
	// CommunityLike is a globally accessible object for table xy_community_like operations.
	CommunityLike = communityLikeDao{internal.NewCommunityLikeDao()}
)

// Add your custom methods and functionality below.
