// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// communityCategoryDao is the data access object for the table xy_community_category.
// You can define custom methods on it to extend its functionality as needed.
type communityCategoryDao struct {
	*internal.CommunityCategoryDao
}

var (
	// CommunityCategory is a globally accessible object for table xy_community_category operations.
	CommunityCategory = communityCategoryDao{internal.NewCommunityCategoryDao()}
)

// Add your custom methods and functionality below.
