// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// communitySearchLogDao is the data access object for the table xy_community_search_log.
// You can define custom methods on it to extend its functionality as needed.
type communitySearchLogDao struct {
	*internal.CommunitySearchLogDao
}

var (
	// CommunitySearchLog is a globally accessible object for table xy_community_search_log operations.
	CommunitySearchLog = communitySearchLogDao{internal.NewCommunitySearchLogDao()}
)

// Add your custom methods and functionality below.
