// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// communityReplyDao is the data access object for the table xy_community_reply.
// You can define custom methods on it to extend its functionality as needed.
type communityReplyDao struct {
	*internal.CommunityReplyDao
}

var (
	// CommunityReply is a globally accessible object for table xy_community_reply operations.
	CommunityReply = communityReplyDao{internal.NewCommunityReplyDao()}
)

// Add your custom methods and functionality below.
