// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// demoArticleDao is the data access object for the table xy_demo_article.
// You can define custom methods on it to extend its functionality as needed.
type demoArticleDao struct {
	*internal.DemoArticleDao
}

var (
	// DemoArticle is a globally accessible object for table xy_demo_article operations.
	DemoArticle = demoArticleDao{internal.NewDemoArticleDao()}
)

// Add your custom methods and functionality below.
