// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// memberCheckinDao is the data access object for the table xy_member_checkin.
// You can define custom methods on it to extend its functionality as needed.
type memberCheckinDao struct {
	*internal.MemberCheckinDao
}

var (
	// MemberCheckin is a globally accessible object for table xy_member_checkin operations.
	MemberCheckin = memberCheckinDao{internal.NewMemberCheckinDao()}
)

// Add your custom methods and functionality below.
