// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// memberMenuDao is the data access object for the table xy_member_menu.
// You can define custom methods on it to extend its functionality as needed.
type memberMenuDao struct {
	*internal.MemberMenuDao
}

var (
	// MemberMenu is a globally accessible object for table xy_member_menu operations.
	MemberMenu = memberMenuDao{internal.NewMemberMenuDao()}
)

// Add your custom methods and functionality below.
