// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// memberNoticeDao is the data access object for the table xy_member_notice.
// You can define custom methods on it to extend its functionality as needed.
type memberNoticeDao struct {
	*internal.MemberNoticeDao
}

var (
	// MemberNotice is a globally accessible object for table xy_member_notice operations.
	MemberNotice = memberNoticeDao{internal.NewMemberNoticeDao()}
)

// Add your custom methods and functionality below.
