// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// memberLoginLogDao is the data access object for the table xy_member_login_log.
// You can define custom methods on it to extend its functionality as needed.
type memberLoginLogDao struct {
	*internal.MemberLoginLogDao
}

var (
	// MemberLoginLog is a globally accessible object for table xy_member_login_log operations.
	MemberLoginLog = memberLoginLogDao{internal.NewMemberLoginLogDao()}
)

// Add your custom methods and functionality below.
