// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// memberGroupDao is the data access object for the table xy_member_group.
// You can define custom methods on it to extend its functionality as needed.
type memberGroupDao struct {
	*internal.MemberGroupDao
}

var (
	// MemberGroup is a globally accessible object for table xy_member_group operations.
	MemberGroup = memberGroupDao{internal.NewMemberGroupDao()}
)

// Add your custom methods and functionality below.
