// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// memberOauthDao is the data access object for the table xy_member_oauth.
// You can define custom methods on it to extend its functionality as needed.
type memberOauthDao struct {
	*internal.MemberOauthDao
}

var (
	// MemberOauth is a globally accessible object for table xy_member_oauth operations.
	MemberOauth = memberOauthDao{internal.NewMemberOauthDao()}
)

// Add your custom methods and functionality below.
