// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// memberMoneyLogDao is the data access object for the table xy_member_money_log.
// You can define custom methods on it to extend its functionality as needed.
type memberMoneyLogDao struct {
	*internal.MemberMoneyLogDao
}

var (
	// MemberMoneyLog is a globally accessible object for table xy_member_money_log operations.
	MemberMoneyLog = memberMoneyLogDao{internal.NewMemberMoneyLogDao()}
)

// Add your custom methods and functionality below.
