// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// memberNoticeReadDao is the data access object for the table xy_member_notice_read.
// You can define custom methods on it to extend its functionality as needed.
type memberNoticeReadDao struct {
	*internal.MemberNoticeReadDao
}

var (
	// MemberNoticeRead is a globally accessible object for table xy_member_notice_read operations.
	MemberNoticeRead = memberNoticeReadDao{internal.NewMemberNoticeReadDao()}
)

// Add your custom methods and functionality below.
