// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// memberScoreLogDao is the data access object for the table xy_member_score_log.
// You can define custom methods on it to extend its functionality as needed.
type memberScoreLogDao struct {
	*internal.MemberScoreLogDao
}

var (
	// MemberScoreLog is a globally accessible object for table xy_member_score_log operations.
	MemberScoreLog = memberScoreLogDao{internal.NewMemberScoreLogDao()}
)

// Add your custom methods and functionality below.
