// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// sysGenCodesColumnDao is the data access object for the table xy_sys_gen_codes_column.
// You can define custom methods on it to extend its functionality as needed.
type sysGenCodesColumnDao struct {
	*internal.SysGenCodesColumnDao
}

var (
	// SysGenCodesColumn is a globally accessible object for table xy_sys_gen_codes_column operations.
	SysGenCodesColumn = sysGenCodesColumnDao{internal.NewSysGenCodesColumnDao()}
)

// Add your custom methods and functionality below.
