// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// testOrderDao is the data access object for the table xy_test_order.
// You can define custom methods on it to extend its functionality as needed.
type testOrderDao struct {
	*internal.TestOrderDao
}

var (
	// TestOrder is a globally accessible object for table xy_test_order operations.
	TestOrder = testOrderDao{internal.NewTestOrderDao()}
)

// Add your custom methods and functionality below.
