// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// testCodecDao is the data access object for the table xy_test_codec.
// You can define custom methods on it to extend its functionality as needed.
type testCodecDao struct {
	*internal.TestCodecDao
}

var (
	// TestCodec is a globally accessible object for table xy_test_codec operations.
	TestCodec = testCodecDao{internal.NewTestCodecDao()}
)

// Add your custom methods and functionality below.
