// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// testCodeDao is the data access object for the table xy_test_code.
// You can define custom methods on it to extend its functionality as needed.
type testCodeDao struct {
	*internal.TestCodeDao
}

var (
	// TestCode is a globally accessible object for table xy_test_code operations.
	TestCode = testCodeDao{internal.NewTestCodeDao()}
)

// Add your custom methods and functionality below.
